using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tile : MonoBehaviour
{
    [SerializeField] private Color _baseColor, _offsetColor;
    [SerializeField] private SpriteRenderer _renderer;
    [SerializeField] private GameObject _highlight;

    private void Start()
    {

    }

    public void Init(Vector2 pos)
    {
        _renderer.color = ((pos.x + pos.y) % 2 == 0) ? _baseColor : _offsetColor;
    }

    private void OnMouseEnter()
    {
        _highlight.SetActive(true);
    }

    private void OnMouseExit()
    {
        _highlight.SetActive(false);
    }

    private void OnMouseDown()
    {
        if (!InputManager.instance.isHoveringUI && !InputManager.instance.UIisOpened)
        GameManager.instance.HandleClickOnTile(InputManager.instance.mouseWorldPosition);
    }
}
